name: video-transcription-api
description: "API de Transcrição de Vídeos com Automação Completa para Google Drive"
version: "1.0.0"

services:
  - name: video-transcription-api
    image: python:3.11-slim
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}
      - DESTINATION_EMAIL=${DESTINATION_EMAIL}
      - BUILD_DATE=${BUILD_DATE}
    volumes:
      - ./:/app
    working_dir: /app
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FORCE_REBUILD: "2024-01-17-20:30"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 4096M
          cpu: 2000m
        reservations:
          memory: 2048M
          cpu: 1000m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  - name: downloads
    driver: local
  - name: transcriptions
    driver: local
  - name: temp
    driver: local 